Repository FRONT-END-BOOTCAMP-PLUS-5/Ssemtle, pull requests merged in 2025-08, with the labels that each got.

#4 fix: GitHub Actions에서 npm install --frozen-lockfile을 npm ci로 수정
  .github/workflows/build-check.yml
Labels: bug

#1 feat: Prisma 설정 및 의존성 설치
  .gitignore
  package-lock.json
  package.json
  prisma/schema.prisma
Labels: enhancement

#3 feat: prisma 스키마 마이그레이션 파일 추가
  .claude/settings.json
  prisma/migrations/20250805163017_seed_dev/migration.sql
  prisma/migrations/migration_lock.toml
Labels: feat

#13 feat: 사용자 등록 API에 클린 아키텍처 적용
  app/api/auth/[...nextauth]/route.ts
  app/api/auth/register/route.ts
  auth.ts
  backend/auth/dtos/UserDto.ts
  backend/auth/usecases/UserUsecase.ts
  backend/common/domains/entities/OwnPet.ts
  backend/common/domains/entities/Pet.ts
  backend/common/domains/entities/Solve.ts
  backend/common/domains/entities/Store.ts
  backend/common/domains/entities/TeacherAuthorization.ts
  backend/common/domains/entities/TeacherStudent.ts
  backend/common/domains/entities/Unit.ts
  backend/common/domains/entities/UnitExam.ts
  backend/common/domains/entities/UnitExamAttempt.ts
  backend/common/domains/entities/UnitQuestion.ts
  backend/common/domains/entities/UnitSolve.ts
  backend/common/domains/entities/User.ts
  backend/common/domains/repositories/IUserRepository.ts
  backend/common/infrastructures/.gitkeep
  backend/common/infrastructures/repositories/PrUserRepository.ts
  backend/temp/dtos/.gitkeep
  backend/temp/usecases/.gitkeep
  eslint.config.mjs
  jest.config.mjs
  jest.setup.js
  libs/prisma.ts
  middleware.ts
  package-lock.json
  package.json
  prisma/schema.prisma
  tests/__mocks__/prisma.ts
  tests/e2e/auth-flow.test.ts
  tests/helpers/test-db.ts
  tests/integration/auth-api.test.ts
  tests/unit/auth.test.ts
  types/next-auth.d.ts
  utils/.gitkeep
Labels: feat, BE

#32 feat: NextAuth 인증 로직 구현 및 프로젝트 가이드라인 업데이트
  CLAUDE.md
  auth.ts
Labels: feat, BE

#36 feat/ Solve 제출 API에서 프론트 상태 기반 문제 제출 및 isCorrect 계산 로직 구현
  app/api/solves/route.ts
Labels: feat, BE

#39 선생님 인증 생성 API 구현
  app/api/admin/teacher/route.ts
  app/api/admin/unit/route.ts
  backend/admin/teacher/dtos/CreateTeacherAuthDto.ts
  backend/admin/teacher/usecases/CreateTeacherAuthUseCase.ts
  backend/admin/unit/UseCases/CreateUnitUseCase.ts
  backend/admin/unit/UseCases/DeleteUnitUseCase.ts
  backend/admin/unit/UseCases/SelectUnitUseCase.ts
  backend/admin/unit/UseCases/UpdateUnitUseCase.ts
  backend/common/domains/repositories/IAdmTchrAuthCreateRepository.ts
  backend/common/domains/repositories/IAdminUnitRepository.ts
  backend/common/infrastructures/repositories/PrAdmTchrAuthCreateRepository.ts
  backend/common/infrastructures/repositories/prAdminUnitRepository.ts
Labels: feat, BE

#44 선생님 등록 삭제 API 구현
  app/api/admin/teacher/route.ts
  backend/admin/teacher/usecases/CreateTeacherAuthUseCase.ts
  backend/admin/teacher/usecases/DeleteTeacherAuthUseCase.ts
  backend/admin/teacher/usecases/SelectTeacherAuthListUseCase.ts
  backend/common/domains/repositories/IAdmTchrAuthRepository.ts
  backend/common/infrastructures/repositories/PrAdmTchrAuthRepository.ts
Labels: feat, BE

#46 feat: lint-staged 라이브러리 추가 및 Husky 설정 개선
  .husky/pre-commit
  .lintstagedrc
  backend/common/infrastructures/repositories/PrSolveRepository.ts
  package-lock.json
  package.json
  tests/integration/auth-api.test.ts
Labels: feat, style

#63 feat: Solves API 기반 설정 완료
  app/layout.tsx
  eslint.config.mjs
  libs/cursor.ts
  libs/providers.tsx
  libs/zod/solves.ts
  package-lock.json
  package.json
  prisma/schema.prisma
  prisma/seed.ts
Labels: feat, BE

#72 feat: 단원평가 문제 생성 및 저장
  app/api/unit-exam/generate/route.ts
  app/api/unit-exam/questions/route.ts
  app/api/unit-exam/submit/route.ts
  app/api/unit-exam/verify/route.ts
  app/unit-test/page.tsx
  backend/common/domains/repositories/IUnitSolveRepository.ts
  backend/common/infrastructures/repositories/PrUnitSolveRepository.ts
  backend/unit/UseCases/UnitExamUsecase.ts
  backend/unit/dtos/UnitExamDto.ts
Labels: fix, feat, BE

#64 feat: Solves API 라우트 구현 - 커서 페이지네이션 및 통계 API
  .lintstagedrc
  app/api/solves/list/route.ts
  app/api/solves/mode/[mode]/route.ts
  app/api/solves/route.ts
  app/api/solves/stats/units/route.ts
  app/api/solves/summary/units/route.ts
  backend/common/domains/repositories/SolveRepository.ts
  backend/common/infrastructures/repositories/PrSolveRepository.ts
  backend/solves/dtos/SolveDto.ts
  backend/solves/usecases/SolvesUseCases.ts
  prisma/seed.ts
  tests/unit/solves-usecases.test.ts
Labels: feat, BE

#71 unit 삭제 시 외래키 제약 조건 문제 해결 및 unit 삭제/수정 api path parameter 방식으로 변경
  app/api/admin/unit/[id]/route.ts
  app/api/admin/unit/route.ts
  backend/admin/teacher/usecases/CreateTeacherAuthUseCase.ts
  backend/admin/unit/UseCases/CreateUnitUseCase.ts
  backend/common/domains/repositories/IAdmTchrAuthRepository.ts
  backend/common/domains/repositories/IAdminUnitRepository.ts
  backend/common/infrastructures/repositories/PrAdmTchrAuthRepository.ts
  backend/common/infrastructures/repositories/prAdminUnitRepository.ts
  prisma/schema.prisma
Labels: refactor, BE

#82 chore: tailwindcss postcss 등 추가, 관련 설정 및 잡다한 코드 조금 설정
  app/globals.css
  app/layout.tsx
  package-lock.json
  package.json
  postcss.config.mjs
Labels: feat, chore

#84 prettier-plugin-tailwind, react-icons 추가
  .prettierrc
  package-lock.json
  package.json
Labels: chore, style

#85 Feat/components
  app/_components/header/Header.tsx
  app/globals.css
  app/layout.tsx
  app/mypage/page.tsx
  app/page.module.css
  public/fonts/BMJUA.ttf
  public/fonts/PretendardVariable.woff2
  public/icons/.gitkeep
  public/logos/Ssemtle_logo.png
Labels: feat, FE

#100 선생님 승인 리스트, 인증 승인, 거절 기능 구현
  app/admin/teacher-approvals/TechApproval.tsx
  app/admin/teacher-approvals/TechReject.tsx
  app/admin/teacher-approvals/page.tsx
  app/api/admin/teachers/route.ts
  app/test-error-notes/page.tsx
  backend/admin/teachers/dtos/TeacherAuthDto.ts
  how HEAD~2
  next.config.ts
Labels: feat, FE

#103 feat: 사이드바 퍼블리싱 완료
  app/_components/sidebar/SidebarAdmin.tsx
  app/_components/sidebar/SidebarTeacher.tsx
  app/_components/sidebar/SidebarUser.tsx
  app/globals.css
  app/unit-exam/page.tsx
Labels: feat, FE

#98 Feat/problem solving page implementation
  app/_components/FilterDropdown.tsx
  app/_components/cards/TestCard.tsx
  app/problem-solving/error.tsx
  app/problem-solving/loading.tsx
  app/problem-solving/page.tsx
  hooks/useInfiniteGets.ts
  hooks/useIntersectionObserver.ts
  libs/providers.tsx
  middleware.ts
  package.json
  scripts/seed-infinite-scroll-data.ts
Labels: feat, FE

#106 chore: 스키마 파일 업데이트
  app/api/admin/teachers/route.ts
  backend/admin/teachers/usecases/CreateTeacherAuthUsecase.ts
  backend/common/domains/entities/TeacherAuthorization.ts
  backend/common/domains/repositories/IAdmTchrAuthRepository.ts
  backend/common/infrastructures/repositories/PrAdmTchrAuthRepository.ts
  prisma/schema.prisma
Labels: feat, BE

#120 style: 사이드바 및 단원평가 퍼블리싱
  app/_components/header/Header.tsx
  app/_components/sidebar/HeaderSizeObserver.tsx
  app/_components/sidebar/RoleBasedSidebar.tsx
  app/_components/sidebar/SidebarAdmin.tsx
  app/_components/sidebar/SidebarTeacher.tsx
  app/_components/sidebar/SidebarUser.tsx
  app/globals.css
  app/layout.tsx
  app/unit/page.tsx
  package-lock.json
  package.json
Labels: fix, feat, FE, refactor, style

#122 feat: 로그인 회원가입 프로세스 구현
  app/_components/auth/DuplicateChecker.tsx
  app/_components/auth/ImageUpload.tsx
  app/_components/auth/SignInForm.tsx
  app/_components/auth/SignUpForm.tsx
  app/_components/auth/TeacherSignUpForm.tsx
  app/signin/page.tsx
  app/signup/page.tsx
  app/signup/students/page.tsx
  app/signup/teacher/page.tsx
  app/signup/teacher/pending/page.tsx
  libs/api/auth.ts
  libs/zod/auth.ts
Labels: feat, FE

#136 style/로그인 페이지 회원가입페이지 가운데정렬
  app/signin/page.tsx
  app/signup/page.tsx
  app/signup/students/page.tsx
  app/signup/teacher/page.tsx
Labels: FE, style

#146 style/practice-catagory 문제풀기-카테고리 페이지 퍼블리싱
  app/api/attendances/today/route.ts
  app/globals.css
  app/practice-catagory/components/ProgressBar.tsx
  app/practice-catagory/components/SearchInput.tsx
  app/practice-catagory/components/categoryCard.tsx
  app/practice-catagory/page.tsx
  backend/attendances/domains/repositories/AttendanceRepository.ts
  backend/attendances/usecases/GetTodayAttendanceUsecase.ts
  backend/common/infrastructures/repositories/PrAttendanceRepository.ts
Labels: feat, FE, style

#156 style: 연습 페이지 UI/UX 개선
  app/_components/molecules/AnswerSection.tsx
  app/_components/molecules/HelpModal.tsx
  app/_components/molecules/HelpSection.tsx
  app/_components/molecules/MathInput.tsx
  app/_components/molecules/NumberPad.tsx
  app/_components/molecules/ProblemDisplay.tsx
  app/_components/organisms/PracticeInterface.tsx
  app/_components/practice/PracticePageContent.tsx
  app/practice/page.tsx
  app/problem-solving/error.tsx
  app/problem-solving/loading.tsx
  app/problem-solving/page.tsx
  app/signin/page.tsx
  app/signup/page.tsx
  app/signup/students/page.tsx
  app/signup/teacher/page.tsx
  app/signup/teacher/pending/page.tsx
Labels: FE, style

#155 Style/mypage 반응형 구현하기
  app/mypage/[id]/page.tsx
Labels: FE, style

#157 Style/admin-unit-exam-code 퍼블리싱 및 API 연동 완료
  app/admin/unit-exam-codes/components/CreateUnitExamModal.tsx
  app/admin/unit-exam-codes/components/ProblemsModal.tsx
  app/admin/unit-exam-codes/components/TableHeader.tsx
  app/admin/unit-exam-codes/components/UnitExamCodeTable.tsx
  app/admin/unit-exam-codes/page.tsx
  app/api/admin/unit-exam-codes/[code]/route.ts
  app/api/admin/unit-exam-codes/route.ts
  backend/unit/Usecases/UnitExamUsecase.ts
Labels: feat, FE, style, BE

#162 feat: 단원평가 및 오답노트 시스템 구현 - 모바일 최적화 드래그 인터페이스
  app/_components/molecules/AnswerSection.tsx
  app/_components/molecules/MathInput.tsx
  app/_components/organisms/UnitInterface.tsx
  app/_components/templates/PracticePageContent.tsx
  app/_components/templates/UnitPageContent.tsx
  app/error-note/_components/ContextualHelpSection.tsx
  app/error-note/_components/ErrorNoteCard.tsx
  app/error-note/_components/ErrorNoteInterface.tsx
  app/error-note/_components/VirtualKeyboard.tsx
  app/error-note/page.tsx
  app/globals.css
  app/practice/page.tsx
  app/unit-exam/page.tsx
Labels: fix, feat, FE

#163 Style/admin unit exam code 코드 형태 변경에 따른 코드 수정
  app/admin/unit-exam-codes/components/CreateUnitExamModal.tsx
  app/admin/unit-exam-codes/components/TableHeader.tsx
  app/admin/unit-exam-codes/components/UnitExamCodeTable.tsx
  app/admin/unit-exam-codes/page.tsx
  app/api/admin/unit-exam-codes/[code]/route.ts
  app/api/admin/unit-exam-codes/route.ts
  app/api/unit-exam/generate/route.ts
  app/api/unit-exam/questions/route.ts
  app/api/unit-exam/submit/route.ts
  app/unit/page.tsx
  backend/unit/Usecases/UnitExamUsecase.ts
  backend/unit/dtos/UnitExamDto.ts
Labels: fix, feat, FE, style, BE

#167 style/unit 단원평가 결과 확인 추가
  app/api/unit-exam/questions/route.ts
  app/api/unit-exam/solves/route.ts
  app/api/unit-exam/submit/route.ts
  app/unit-result/page.tsx
  app/unit-test/page.tsx
  app/unit/page.tsx
  backend/unit/Usecases/UnitExamUsecase.ts
Labels: fix, feat, FE, style, BE

#169 role 기반 페이지 라우팅 접근 제한
  middleware.ts
Labels: feat, FE

#174 feat: 단위 시험에 타이머 기능 추가
  app/_components/templates/UnitPageContent.tsx
  app/unit-exam/_components/ExamCountdown.tsx
  hooks/useCountdown.ts
  hooks/useTimer.ts
  libs/formatDuration.ts
Labels: feat, FE, style

#190 선생님/관리자 페이지 버튼들 pointer 적용
  app/_components/pagination/Pagination.tsx
  app/admin/unit/components/CreateUnitModal.tsx
  app/admin/unit/components/UnitCard.tsx
  app/admin/unit/page.tsx
  app/teacher/student/components/ActionButtons.tsx
  app/teacher/student/components/BulkRegisterModal.tsx
  app/teacher/student/components/DeleteStudentIcon.tsx
  app/teacher/student/components/ExportButton.tsx
  app/teacher/student/components/RegisterModal.tsx
  app/teacher/student/components/StudentTable.tsx
  app/teacher/student/page.tsx
Labels: FE, style

#183 Style/unit result 페이지 리펙토링 및 연동
  .gitignore
  app/_components/sidebar/SidebarAdmin.tsx
  app/_components/sidebar/SidebarTeacher.tsx
  app/_components/sidebar/SidebarUser.tsx
  app/practice-category/components/SearchInput.tsx
  app/practice-category/components/categoryCard.tsx
  app/practice-category/page.tsx
  app/unit-result/page.tsx
  app/unit/page.tsx
  backend/unit/Usecases/UnitExamUsecase.ts
Labels: feat, FE, style, BE

#194 fix: UnitPageContent의 검증에 문제가 있다면 집으로 보내는 것으로 변경
  app/_components/templates/UnitPageContent.tsx
Labels: fix, feat, FE

#192 feat: redirectURL 추가
  app/_components/templates/UnitPageContent.tsx
Labels: feat, FE

#205 내보내기 알림 문구 추가 및 토스트 메세지 적용
  app/admin/teacher-approval/components/TechApproval.tsx
  app/admin/teacher-approval/components/TechReject.tsx
  app/admin/unit/components/CreateUnitModal.tsx
  app/admin/unit/components/EditUnitModal.tsx
  app/admin/unit/page.tsx
  app/teacher/student/components/ExportButton.tsx
Labels: feat, FE, style

#208 선생님 승인 거절 시 게정 삭제
  backend/admin/teachers/usecases/DeleteTeacherAuthUsecase.ts
  backend/common/domains/repositories/IAdmTchrAuthRepository.ts
  backend/common/infrastructures/repositories/PrAdmTchrAuthRepository.ts
Labels: feat, BE

#207 feat: 로그인 UI 변경, 토스트 적용, 로그인 엔터로 submit 적용
  app/_components/auth/SignInForm.tsx
  app/signin/page.tsx
Labels: feat, FE, style

#213 style: CSS 정리 및 사용자 경험 개선
  app/_components/auth/SignInForm.tsx
  app/_components/auth/SignUpForm.tsx
  app/_components/auth/TeacherSignUpForm.tsx
  app/_components/molecules/HelpModal.tsx
  app/_components/molecules/HelpSection.tsx
  app/_components/organisms/PracticeInterface.tsx
  app/_components/templates/UnitPageContent.tsx
  app/admin/teacher-approval/components/TechReject.tsx
  app/signup/teacher/pending/page.tsx
  app/unit-result/page.tsx
Labels: feat, FE, refactor, style

#214 Style/practice catagory 토스트 메세지 추가 및 DB 데이터 추가 로직 수정
  app/api/unit-exam/questions/route.ts
  app/practice-category/components/categoryCard.tsx
  app/practice-category/page.tsx
  app/unit-test/page.tsx
  app/unit/page.tsx
  backend/unit/Usecases/UnitExamUsecase.ts
Labels: fix, FE, refactor, BE

#223 랜딩 페이지 반응형 구현
  app/landing/landing-logo/LandingLogo.tsx
  app/landing/page.tsx
Labels: FE, style

#222 Style: 수식 자판의 변수 버튼 더 변수 표시처럼 바꾸기
  app/_components/molecules/NumberPad.tsx
  app/error-note/_components/VirtualKeyboard.tsx
Labels: style

#236 feat: problem-solving 렌딩페이지 추가
  app/landing/landing-sphere/ProblemSolvingSphere.tsx
  app/landing/page.tsx
Labels: feat, FE

#232 랜딩 페이지 particle
  app/_components/404/NotFoundPage.tsx
  app/landing/landing-logo/LandingLogo.tsx
  app/landing/landing-logo/components/LogoAnimation.tsx
  app/landing/landing-logo/components/ScrollIndicator.tsx
  app/landing/landing-logo/components/TextAnimated.tsx
  hooks/useParticle.ts
  package-lock.json
  package.json
  types/canvas-confetti.d.ts
  utils/logs/logos.ts
Labels: FE, style

#250 style: 레이아웃 수정
  app/signup/page.tsx
  app/signup/students/page.tsx
  app/signup/teacher/page.tsx
Labels: style

#251 Chore/update dev
  .github/workflows/main.yml
Labels: chore

#256 학생 관리 토스트 메세지 적용 및 콘솔 제거
  app/teacher/student/components/BulkRegisterModal.tsx
  app/teacher/student/components/DeleteStudentIcon.tsx
  app/teacher/student/components/RegisterModal.tsx
Labels: feat, FE

#257 fix: 단원평가 프롬프트 수정 및 테스트페이지 삭제
  app/_components/sidebar/RoleBasedSidebar.tsx
  app/_components/sidebar/RoleConsole.tsx
  backend/unit/Usecases/UnitExamUsecase.ts
Labels: fix, FE, refactor
