Repository FRONT-END-BOOTCAMP-PLUS-5/Ssemtle, pull requests merged in 2025-09, with the labels that each got.

#267 style : UI/UX 디자인시스템 적용 및 모바일 기준 1180으로 상향조정
  app/_components/header/Header.tsx
  app/_components/layoutclient/LayoutClient.tsx
  app/_components/layoutclient/MainContainer.tsx
  app/globals.css
  app/layout.tsx
Labels: refactor, style

#268 develop
  app/_components/header/Header.tsx
  app/_components/layoutclient/LayoutClient.tsx
  app/_components/layoutclient/MainContainer.tsx
  app/globals.css
  app/layout.tsx
Labels: refactor, style

#270 chore: test-calendar 페이지 삭제
  app/test-calendar/page.tsx
Labels: FE

#272 feat: Tailwind 폰트 크기 20% 증가 및 테마 변수 적용
  app/admin/teacher-approval/page.tsx
  app/admin/unit/page.tsx
  app/globals.css
  app/mypage/components/CalenderComponent.tsx
  app/teacher/student/components/SearchInput.tsx
  app/teacher/student/components/StudentTable.tsx
  app/teacher/unit-exam-codes/components/UnitExamCodeTable.tsx
Labels: FE, style

#276 style/practice-category UI/UX 수정 및 코드 리팩토링
  app/practice-category/components/SearchInput.tsx
  app/practice-category/components/unitMeta.ts
  app/practice-category/page.tsx
Labels: FE, refactor, style

#278 style/unit 레이아웃 변경에 따른 UI/UX 조정
  app/unit/page.tsx
Labels: FE, style

#279 refactor: Prisma Client 커스텀 출력 경로 적용
  app/api/admin/unit-exam-codes/route.ts
  app/api/solves/list/[id]/route.ts
  backend/common/infrastructures/repositories/PrAdmTchrAuthRepository.ts
  backend/common/infrastructures/repositories/PrAuthRepository.ts
  backend/common/infrastructures/repositories/PrSolveRepository.ts
  backend/common/infrastructures/repositories/PrTeacherStudentRepository.ts
  backend/common/infrastructures/repositories/PrUnitExamAnalysisRepository.ts
  backend/common/infrastructures/repositories/PrUnitExamAttemptRepository.ts
  backend/common/infrastructures/repositories/PrUnitExamRepository.ts
  backend/common/infrastructures/repositories/PrUnitQuestionRepository.ts
  backend/common/infrastructures/repositories/PrUnitRepository.ts
  backend/common/infrastructures/repositories/PrUnitSolveRepository.ts
  backend/common/infrastructures/repositories/PrUserRepository.ts
  backend/common/infrastructures/repositories/prAdminUnitRepository.ts
  libs/prisma.ts
  prisma/schema.prisma
  prisma/seed.ts
  scripts/seed-infinite-scroll-data.ts
Labels: refactor

#281 feat: 교사 회원가입에 이메일 필드 추가
  app/_components/auth/TeacherSignUpForm.tsx
  app/api/admin/teachers/route.ts
  app/signup/teacher/pending/page.tsx
  backend/admin/teachers/usecases/CreateTeacherAuthUsecase.ts
  backend/common/domains/entities/TeacherAuthorization.ts
  backend/common/domains/repositories/IAdmTchrAuthRepository.ts
  backend/common/infrastructures/repositories/PrAdmTchrAuthRepository.ts
  libs/api/auth.ts
  libs/zod/auth.ts
  prisma/schema.prisma
Labels: feat, FE, style, BE

#282 Style/sidebar && 햄버거버튼 위치옮기기
  app/_components/header/Header.tsx
  app/_components/layoutclient/LayoutClient.tsx
  app/_components/sidebar/SidebarAdmin.tsx
  app/_components/sidebar/SidebarTeacher.tsx
  app/_components/sidebar/SidebarUser.tsx
  app/globals.css
  app/mypage/[id]/page.tsx
Labels: style

#291 선생님 가입 승인 대기자 라우팅 처리
  middleware.ts
Labels: feat, BE

#293 fix: 단원평가 렌더링 이슈 해결.
  app/_components/templates/UnitPageContent.tsx
  app/workbook/unit-exam/UnitExamDataProvider.tsx
  package-lock.json
Labels: fix, FE, BE

#302 선생님 승인 거절 시 이메일 알림 발송
  app/admin/teacher-approval/components/TechReject.tsx
  app/api/admin/teachers/route.ts
  backend/admin/teachers/usecases/DeleteTeacherAuthUsecase.ts
  backend/common/domains/repositories/IEmailService.ts
  backend/common/infrastructures/services/ResendEmailService.ts
  package-lock.json
  package.json
Labels: feat, FE, BE

#299 fix: 단원평가 결과 페이지 미응시 내역 안나오는 버그 수정
  app/api/unit-exam/solves/route.ts
  app/unit-result/page.tsx
Labels: fix, FE, BE

#303 main 최신화
  app/_components/layoutclient/LayoutClient.tsx
  app/_components/molecules/AnswerSection.tsx
  app/_components/molecules/HelpModal.tsx
  app/_components/molecules/MathInput.tsx
  app/_components/sidebar/SidebarAdmin.tsx
  app/_components/sidebar/SidebarTeacher.tsx
  app/_components/sidebar/SidebarUser.tsx
  app/_components/templates/UnitPageContent.tsx
  app/admin/teacher-approval/components/TechReject.tsx
  app/admin/teacher-approval/page.tsx
  app/admin/unit/page.tsx
  app/api/admin/teachers/route.ts
  app/api/unit-exam/solves/route.ts
  app/error-note/_components/ErrorNoteCard.tsx
  app/error-note/_components/ErrorNoteInterface.tsx
  app/error-note/_components/VirtualKeyboard.tsx
  app/mypage/[id]/error-note/MyPageErrorNote.tsx
  app/mypage/[id]/page.tsx
  app/unit-result/page.tsx
  app/workbook/unit-exam/UnitExamDataProvider.tsx
  backend/admin/teachers/usecases/DeleteTeacherAuthUsecase.ts
  backend/common/domains/repositories/IEmailService.ts
  backend/common/infrastructures/services/ResendEmailService.ts
  backend/solves/usecases/GenerateSolvesByUnitUsecase.ts
  middleware.ts
  package-lock.json
  package.json
Labels: bug, fix, feat, FE, refactor, style, BE

#307 feat: VirtualKeyboard 오버레이 수정 및 키보드 감지 기능 구현
  app/_components/organisms/PracticeInterface.tsx
  app/_components/organisms/UnitInterface.tsx
  app/_components/templates/UnitPageContent.tsx
  app/_hooks/useKeyboardDetection.ts
  app/error-note/_components/ContextualHelpSection.tsx
  app/error-note/_components/ErrorNoteInterface.tsx
  app/landing/landing-trial/InteractiveLanding.tsx
  app/mypage/[id]/error-note/MyPageErrorNote.tsx
Labels: feat, FE, style

#308 fix: sidebar callbackUrl -> redirectTo (deprecated 코드), ToastContainer Props 변경
  app/_components/sidebar/SidebarAdmin.tsx
  app/_components/sidebar/SidebarTeacher.tsx
  app/_components/sidebar/SidebarUser.tsx
  app/layout.tsx
Labels: fix, FE

#312 refactor: 오답노트 컴포넌트 통합 및 도움말/가상키보드 개선
  app/_components/error-note/ContextualHelpSection.tsx
  app/_components/error-note/DragHandle.tsx
  app/_components/error-note/ErrorNoteCard.tsx
  app/_components/error-note/ErrorNoteInterface.tsx
  app/_components/error-note/HelpContentDisplay.tsx
  app/_components/error-note/VideoSection.tsx
  app/_components/error-note/VirtualKeyboard.tsx
  app/_components/error-note/createMyPageConfig.ts
  app/error-note/_components/ContextualHelpSection.tsx
  app/error-note/page.tsx
  app/mypage/[id]/error-note/MyPageErrorNote.tsx
  app/mypage/[id]/error-note/MyPageErrorNoteWrapper.tsx
  app/mypage/[id]/error-note/page.tsx
  hooks/useDragAndDrop.ts
  hooks/useHelpContent.ts
  hooks/useMediaQuery.ts
  hooks/usePositioning.ts
Labels: fix, FE, refactor
