Repository FRONT-END-BOOTCAMP-PLUS-5/Ssemtle, pull requests merged in 2025-10, with the labels that each got.

#313 Refactor/readme
  README.md
  app/_components/templates/PracticePageContent.tsx
  app/api/solves/route.ts
  backend/common/infrastructures/LLM/callGemini.ts
Labels: bug

#317 단원평가 모바일 버전 학생 조회 URL 경로 수정
  app/teacher/student/components/StudentTable.tsx
Labels: fix, FE

#322 Update README.md
  README.md
Labels: docs

#319 feat: Docker/Kubernetes 기반 프로덕션 배포 인프라 구축
  .dockerignore
  .github/workflows/deploy.yml
  Dockerfile
  app/api/healthz/route.ts
  app/api/readyz/route.ts
  k8s/MIGRATION_NOTES.md
  k8s/README.md
  k8s/database.yaml
  k8s/deployment.yaml
  k8s/ingress.yaml
  k8s/service.yaml
  next.config.ts
  prisma/schema.prisma
Labels: feat, FE, BE
